#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 RS-Key contributors
"""Hold every published sentence about a registered property to the registry.

Stage 0 п.3 and the last exit of stage 4 are ONE predicate — "a public claim
about a P0-family id is generated from the registry; one written by hand fails on
a docs row" — and it was closed by nothing. Measured before this file existed:
four false hand-written sentences, including "`SEC-FIDO-001` … PROVEN on
hardware" in `README.md`, gave EXIT=0 on all eight gates, because `scripts/
check.sh` carried no docs row at all and the CI step `docs.sh check` is `mdbook
build` plus `lychee --offline`.

**The literal criterion is not the one implemented, and the difference is stated
rather than hidden.** "Every sentence is GENERATED" would refuse
`docs/store-refinement.md`'s "which is why `SEC-STORE-002` is `BOUNDED` and not
more" — a true sentence doing work no generated table does. What is implemented
is the half that carries the risk: a hand-written status is accepted only when it
is the status the registry HOLDS for the id in the same sentence. So a true copy
stays and stops being able to rot; a copy that is wrong the day it is typed is
refused; and `PROVEN`, which is no row's status anywhere in this tree, is refused
of every id by construction — which is the measured failure above.

Two rules, and both are about a COPY:

* a sentence naming registered ids and an evidence word none of them holds is
  refused. Sentence and not paragraph, measured: over the shipped corpus the
  paragraph window reports two refusals and both are contrastive prose — "…
  `SEC-STORE-003` and `SEC-STORE-004` stay MODELLED-ONLY" beside the word
  `BOUNDED` about neither of them — while the sentence window reports zero and
  still catches all three injected false claims;
* a LINE carrying an id, a status and three or more bare integers is a
  transcribed row of the derived evidence vector, and belongs to the generator
  that derives it. `docs/authorization-slice.md` carried three such rows, and
  their `co` column said 0 where the tree says 1: right when typed, wrong within
  the week, and the sentence rule cannot see it because the STATUS half stayed
  true.

What this row does not do: read English. A sentence that overclaims without using
a vocabulary word — "we have proved this holds on the device" — passes, and no
scanner of a natural language closes that. What it does is make the WORDS the
registry owns unusable as a lie about a row that registry holds.
"""

import pathlib
import re
import sys
import tomllib

import run_count_gate

ROOT = pathlib.Path(__file__).resolve().parent.parent
REGISTRY = pathlib.Path("assurance/properties.toml")

#: A registered property id, in the three shapes the registry uses:
#: `SEC-FIDO-001`, the clause rows `SEC-FIDO-006A`, and the liveness rows
#: `SEC-FIDO-L01` — which a pattern anchored on a digit misses, and a test over
#: the registry is what caught that. Narrow on purpose otherwise:
#: `TM-HOST-GATES` and `PLAT-TOOL-004` are other registries' ids and other
#: rules' business.
ID = re.compile(r"\bSEC-[A-Z]+-[A-Z]?\d+[A-C]?\b")

#: The evidence vocabulary a published sentence may put beside an id. The three
#: the registry actually uses come from the registry — [`vocabulary`] takes them
#: from the file, so a new status cannot arrive unseen — and the rest are §4.2's
#: working classes plus the one §4.3 governs. `PROVEN` is here precisely BECAUSE
#: no row holds it: a word that is no id's status is refused of every id, which
#: is what makes the measured README sentence fall.
#:
#: Longest first, so `PROVEN-SOURCE` is never read as `PROVEN` with a suffix.
CLASSES = (
    "PROVEN-SOURCE",
    "BOUNDED-SOURCE",
    "MEASURED-PLATFORM",
    "BINARY-CHECKED",
    "MODEL-CHECKED",
    "MODELLED-ONLY",
    "ACCEPTED-RISK",
    "TRACE-LINKED",
    "CO-REFUTED",
    "MEASURED",
    "BOUNDED",
    "PROVEN",
)

#: Where a sentence ends, for the window this scans. A table cell boundary counts:
#: a generated-looking row is a sequence of independent claims, not one sentence,
#: and reading a whole row as one window let a status in the third column excuse a
#: word in the ninth.
SENTENCE = re.compile(r"(?<=[.;:!?])\s+|\n\s*\n|\|")

#: `<!-- name:start -->` … `<!-- name:end -->`, the shape EVERY generator in this
#: tree marks its regions with. Derived from the shape rather than from a list of
#: generators: a list is one more roster to keep, and this row would then read a
#: new generator's output as hand-written prose.
REGION = re.compile(r"<!--\s*([a-z0-9-]+):start\s*-->")

#: A page some generator writes whole, said in its own first lines. Same reason:
#: the header is the page's own claim about itself, and a roster here would go
#: stale against it.
GENERATED_WHOLE = re.compile(r"Generated by scripts/[a-z_]+\.py")

#: A bare integer, for the transcribed-row rule, counted over the line with its
#: IDS BLANKED: the `007` of `SEC-FIDO-007` is a bare integer by every pattern,
#: and counting it took "`SEC-FIDO-007` is MODELLED-ONLY and 2 of 3
#: configurations check it" to three. Three, because the derived vector's
#: narrowest row still carries `cfgs`, `mut` and `co`.
NUMBER = re.compile(r"(?<![\w.])\d+(?![\w.])")
ROW_NUMBERS = 3

#: True copies the sweep must still find. A PARAMETER of [`audit`] and not a
#: global a case patches down, so the shipped value is the one every case runs
#: against — `SCAN_FLOOR` in `run_count_gate.py` shipped the other way and its own
#: commit message says the shipped 8 was therefore never checked.
#:
#: Under the measured 4. It is a floor on the SCANNER, not on the prose: a
#: masking bug, an empty corpus or a vocabulary that stopped matching all read as
#: "no claims found", which is indistinguishable from a clean tree.
CLAIM_FLOOR = 3

#: Pages the corpus must still hold, for the same reason one layer out: if
#: `run_count_gate.scanned` ever answers a short list, every rule here passes.
#: Under the measured 323.
CORPUS_FLOOR = 250


def vocabulary(root: pathlib.Path) -> tuple[dict, tuple]:
    """({id: status}, the words a claim may use).

    The statuses come from the registry rather than from [`CLASSES`], and the
    check that [`CLASSES`] still contains them is a test's — a status added to the
    registry and not here would otherwise be a word this row silently stops
    reading, which is the failure the whole file is about.
    """
    registry = tomllib.loads((root / REGISTRY).read_text(encoding="utf-8"))
    status = {
        str(row.get("id")): str(row.get("status"))
        for row in registry.get("property", [])
    }
    return status, CLASSES


def mask_regions(text: str) -> str:
    """`text` with every generated region blanked, newlines kept so a reported
    line number still points where it says."""
    out = text
    for found in REGION.finditer(text):
        end = f"<!-- {found.group(1)}:end -->"
        stop = text.find(end, found.start())
        if stop != -1:
            chunk = text[found.start() : stop + len(end)]
            out = out.replace(chunk, "\n" * chunk.count("\n"), 1)
    return out


def corpus(root: pathlib.Path) -> list[tuple[str, str]]:
    """(path, hand-written text) for every published page a claim can be typed in."""
    out = []
    for path in run_count_gate.scanned(root):
        text = path.read_text(errors="replace")
        if GENERATED_WHOLE.search(text[:600]):
            continue
        out.append((str(path.relative_to(root)), mask_regions(text)))
    return out


def line_of(text: str, offset: int) -> int:
    return text.count("\n", 0, offset) + 1


def audit(
    root: pathlib.Path,
    claim_floor: int = CLAIM_FLOOR,
    corpus_floor: int = CORPUS_FLOOR,
) -> tuple[list[str], str]:
    root = pathlib.Path(root)
    findings: list[str] = []
    status, words = vocabulary(root)
    vocab = re.compile(r"\b(" + "|".join(re.escape(w) for w in words) + r")\b")
    pages = corpus(root)
    if len(pages) < corpus_floor:
        findings.append(
            f"the scan reached {len(pages)} page(s), under the floor of"
            f" {corpus_floor} — a corpus that shrank is a rule that stopped"
            " looking, and it reads exactly like a tree with nothing to find"
        )

    held = rows = 0
    for rel, text in pages:
        cursor = 0
        for chunk in SENTENCE.split(text):
            at = text.find(chunk, cursor)
            cursor = at + len(chunk) if at != -1 else cursor
            # Words are scoped to the SENTENCE and ids to the LINES IT TOUCHES,
            # which is not a symmetry lapse. A table row is one line, so a cell
            # sees the row's subject — sentence-scoped ids left
            # `| id | BOUNDED | PROVEN-SOURCE |` unread. A prose sentence wraps,
            # so one line is too narrow — that scope reported the second half of
            # "`SEC-STORE-002` is `BOUNDED`. The other five … stay
            # `MODELLED-ONLY`" as a claim about `SEC-STORE-002`.
            start = text.rfind("\n", 0, max(at, 0)) + 1
            stop = text.find("\n", max(at, 0) + len(chunk))
            span = text[start : stop if stop != -1 else len(text)]
            ids = [i for i in ID.findall(span) if i in status]
            said = set(vocab.findall(chunk))
            if not ids or not said:
                continue
            allowed = {status[i] for i in ids}
            held += len(said & allowed)
            for word in sorted(said - allowed):
                findings.append(
                    f"{rel}:{line_of(text, max(at, 0))}: says `{word}` in a sentence"
                    f" naming {', '.join(sorted(set(ids)))}, whose registered"
                    f" status is {' / '.join(sorted(allowed))} — a hand-written"
                    " status is a copy, and this one is not a copy of anything"
                )
        for number, line in enumerate(text.splitlines(), 1):
            if not (ID.search(line) and vocab.search(line)):
                continue
            bare = NUMBER.findall(ID.sub(" ", line))
            if len(bare) < ROW_NUMBERS:
                continue
            rows += 1
            findings.append(
                f"{rel}:{number}: an id, a status and {len(bare)}"
                " bare numbers on one line is a transcribed row of the derived"
                " evidence vector — it belongs to the generator that derives it,"
                " because the status half can stay true while a column rots"
            )

    if held < claim_floor:
        findings.append(
            f"the scan matched {held} true status copy/copies, under the floor of"
            f" {claim_floor} — the floor is on the SCANNER: a masking bug or a"
            " vocabulary that stopped matching reads as a tree with no claims in it"
        )
    summary = (
        f"claims-gate: ok — {len(pages)} published page(s), {held} hand-written"
        f" status(es) held against the registry, {rows} transcribed row(s)"
    )
    return findings, summary


def main() -> int:
    findings, summary = audit(ROOT)
    if findings:
        print("claims-gate:", file=sys.stderr)
        for finding in findings:
            print(f"  {finding}", file=sys.stderr)
        print(
            "\nA published status is a claim, and the registry is the only place"
            "\nthis tree decides one. Generate the sentence, or make it true.",
            file=sys.stderr,
        )
        return 1
    print(summary)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
